site_name: FaBo JetBot Docs
theme:
    name: material
    custom_dir: 'theme'
    language: 'ja'
    palette:
      primary: 'green'
      accent: 'black'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - fontawesome_markdown
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.keys
  - markdown_fenced_code_tabs
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"  
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
plugins:
  - macros